spring:
  application:
    name: rate-limiter

  datasource:
    url: jdbc:mysql://localhost:3306/rate_limiter
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

rate-limiter:
  max-requests: 5
  window-size-seconds: 60
  algorithm: token-window
  bucket-capacity: 5
  refill-rate: 0.2